### ISSUE TITLE
"union_" cannot compute the union of two polygons

### ISSUE THREAD

**Issue by huntto** [boostorg/geometry#1059]
typedef boost::geometry::model::d2::point_xy<double> point;
typedef boost::geometry::model::polygon<point> polygon;

const double PI = 3.141592653;
void CreateCircularContour(float cx, float cy, float radius, float resolution, polygon &p)
{
    int count = (int)(2 * PI * radius / resolution);
    float rad_delta = 2 * PI / count;
    double rad = 0;
    float fx, fy;
    for (int i = 0; i < count; i++)
    {
        float x = (float)(radius * cos(rad)) + cx;
        float y = (float)(radius * sin(rad)) + cy;
        if (i == 0)
        {
            fx = x;
            fy = y;
        }
        boost::geometry::append(p.outer(), point(x, y));
        rad += rad_delta;
    }
    boost::geometry::append(p.outer(), point(fx, fy));
}

...

    polygon subj;
    CreateCircularContour(200, 200, 50, 2, subj);
    polygon clip;
    CreateCircularContour(300, 300, 100, 2, clip);

    std::list<polygon> output;
    boost::geometry::union_(subj, clip, output);

**Comment by barendgehrels** [comment]
Hi! What do you mean by: “cannot”? Does it compile? Does it crash? What is the result?

also your code does not look well.
‘’’
typedef boost::geometry::model::d2::point_xy point;
typedef boost::geometry::model::polygon polygon
‘’’
Where is the type? Double? Is it clockwise?

**Comment by huntto** [comment]
> Hi! What do you mean by: “cannot”? Does it compile? Does it crash? What is the result?
> 
> also your code does not look well. ‘’’ typedef boost::geometry::model::d2::point_xy point; typedef boost::geometry::model::polygon polygon ‘’’ Where is the type? Double? Is it clockwise?

Thanks for your reply, by changing clockwise to counterclockwise I got a correct polygon instead of an empty one.

**Comment by barendgehrels** [comment]
Good it's solved.

The safest way is to call `boost::geometry::correct` on both polygons before calling `union_`. Then you know the orientation and the closure are right.
