### ISSUE TITLE
Is boost::geom - and its mandatory dependencies - really header only

### ISSUE THREAD

**Issue by JeromeDesfieux** [boostorg/geometry#1072]
I read in the doc the following:
`Boost.Geometry is only dependant on headers-only Boost libraries`
(https://www.boost.org/doc/libs/1_80_0/libs/geometry/doc/html/geometry/compilation.html)

But when I integrate it with CMake I can see that geometry requires math (https://github.com/boostorg/geometry/blob/boost-1.80.0/CMakeLists.txt#L31) which in turn requires random (https://github.com/boostorg/math/blob/45a2cbe789e1b81d310024d58c9616cc434a63d3/CMakeLists.txt#L37) which actually builds a cpp file (https://github.com/boostorg/random/blob/develop/CMakeLists.txt#L10).

It seems it is possible to use a standalone version of math through BOOST_MATH_STANDALONE but I don't manage to active this option. It seems it is always overridden by the cmakedependent criteria.

How can I ensure to use only header only files ?

Here attached my try to install geometry.

[CMakeLists.txt](https://github.com/boostorg/geometry/files/9830368/CMakeLists.txt)

**Comment by mloskot** [comment]
Yes, Boost.Geometry is a header-only library. The fact that some of its, typically optional, dependencies may not be header-only does not the status of BG.

**Comment by JeromeDesfieux** [comment]
OK I see. But then the doc is not actually exact. I don't discuss BG is header only. However the phrase `Boost.Geometry is only dependant on headers-only Boost libraries` is quite missleading / incomplete.

When you say that those dependencies are optional, can you please tell me how I can toggle those modules OFF ?
I am new with boost so maybe my question is obvious !

**Comment by JeromeDesfieux** [comment]
I confirm I can use BG with only header files.
