### ISSUE TITLE
Regression 1.79.0: union operation of two polygons outputs zero polygons

### ISSUE THREAD

**Issue by paulk125** [boostorg/geometry#1103]
I have two polygons. Both are nearly unit squares. One is from (0,epsilon)-(1,1) and the other is from (0,-1)-(1,0). So these two squares are not quite touching. I would expect the geometry union operation to either return one merged polygon or two separate polygons. Instead it returns zero polygons.

Here is a godbolt link to duplicate the problem:
https://godbolt.org/z/P16oKM6Pn

Note that this bug affects 1.79 and later. If you change the compiler option in the godbolt link to include the 1.78 boost headers, then the union operation works fine:

`-I/opt/compiler-explorer/libs/boost_1_78_0`

**Comment by barendgehrels** [comment]
Unit test is added.
