### ISSUE TITLE
Example in release needs boost/geometry/extensions which is not shipped

### ISSUE THREAD

**Issue by sgn** [boostorg/geometry#1104]
Hello,

Can you either ship `boost/geometry/extensions` in the release or remove those examples from release?

As of it is, the example are all useless because it needs  `boost/geometry/extensions`

**Comment by vissarion** [comment]
Thanks for the report. The release you mean is version `1.81.0`. Indeed this is an issue that will be fixed in `1.82.0` (we cannot change/update the current release). See https://github.com/boostorg/geometry/pull/1105.
