### ISSUE TITLE
boost::geometry::intersection algorithm creates spike

### ISSUE THREAD

**Issue by vschoech** [boostorg/geometry#1184]
My `tc::geo::polygon<int>` type is actually a **multi-polygon**, using a polygon type that is based on **int**, oriented **counter-clockwise** and **open** (not closed). I am using **boost 1.79.0**.

Please consider the following example as it occurred in our code: 

```C++
tc::geo::polygon<int> polygonA;
boost::geometry::read_wkt("MULTIPOLYGON(((1169 177,2004 177,2004 1977,1262 1977,1169 177)))", polygonA);
tc::geo::polygon<int> polygonB;
boost::geometry::read_wkt("MULTIPOLYGON(((1179 371,1175 287,1179 287,1179 371)))", polygonB);
tc::geo::polygon<int> polygonC;
boost::geometry::intersection(polygonA, polygonB, polygonC);
tc::geo::polygon<int> polygonD = polygonC;
boost::geometry::remove_spikes(polygonD);
// polygonC=polygon(MULTIPOLYGON(((1179 370,1179 365,1175 287,1179 287,1179 370))))
// polygonD=polygon(MULTIPOLYGON(((1179 365,1175 287,1179 287,1179 365))))
```

It was my expectation that when the input does not contain spikes, neither does the output from boost::geometry::intersection. Please clarify whether my assumption is wrong or there is a bug in boost::geometry::intersection.

See also:
- https://github.com/boostorg/geometry/issues/603
- https://github.com/boostorg/geometry/issues/1022

**Comment by vschoech** [comment]
Thank you for the quick turn-around! I've seen it in 1.79, but I assume you reproduced in 1.83?

**Comment by barendgehrels** [comment]
Yes, it's reproduced in 1.83

**Comment by barendgehrels** [comment]
I've a concept fix, will create a PR later today (if the concept is fine)

**Comment by vschoech** [comment]
@barendgehrels Thank you! :)

**Comment by vschoech** [comment]
We updated our code base to boost 1.87.0 and I'm happy to confirm that I cannot reproduce this issue any more. ✔️
