### ISSUE TITLE
Mandate C++17 by default

### ISSUE THREAD

**Issue by georgthegreat** [boostorg/geometry#1225]
Hi.

At the time boost/geometry mandates C++14 as its default C++ standard.
I wonder if there is a will for raising the bar to C++17.

My rationale is as follows: C++17 introduces std::variant, and boost::geometry is the only client of boost:::variant2 in all our codebase.
Maybe we can switch and remove the dependency?

**Comment by barendgehrels** [comment]
Hi!

No, we cannot do that, at least not yet, there are still customers using C++14

Kind regards, Barend

**Comment by awulkiew** [comment]
@georgthegreat This dependency is optional. As long as you don't explicitly include `<boost/geometry/geometries/adapted/boost_variant2.hpp>` you can remove it from your codebase. Unless I'm missing something.

**Comment by awulkiew** [comment]
If you want to use `std::variant` you can include `<include/boost/geometry/geometries/adapted/std_variant.hpp>`. Even if we required C++17 we wouldn't drop this optional dependency the same way we didn't drop the support for `boost::variant` when we moved to C++14.

**Comment by barendgehrels** [comment]
@awulkiew thanks for the details. Okay, so if I understand it correctly, we just drop adaptation to variant2 and the internal code does not depend on it. That is fine.

**Comment by vissarion** [comment]
Thanks @awulkiew, indeed `boost::variant2` is only included in tests thus an optional dependency. However, `boost::variant` is still a real dependency (for backward compatibility) since `<include/boost/geometry/geometries/adapted/boost_variant.hpp>` is included by (almost) all boost geometry algorithms.
