### ISSUE TITLE
Can't build with geometry.hpp in CLR project

### ISSUE THREAD

**Issue by Sungjun4** [boostorg/geometry#1228]
Visual Studio 2022(2019 as well)
ISO C++ 14, 17, 20
boost: 1.84.0, 1.81.0

I create a new project, CLR class Library(.NET Framework) or CLR console App(.Net Framework), and install the Boost NuGet package(1.84.0)

And include the boost header, even not adding any source code, just including headers.

And build a solution.

Followings are no problem to build

#include <boost/foreach.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/ptree_fwd.hpp>
#include <boost/geometry/arithmetic/cross_product.hpp>
#include <boost/geometry/geometries/geometries.hpp>

But if I add 

#include <boost/geometry.hpp>

Then I got the error.

Error	C1189	#error:  "This library now requires a C++11 or later compiler - this message was generated as a result of BOOST_NO_CXX11_REF_QUALIFIERS being set"	

Is this a bug? or do I need any setting for using geometry.hpp in CLR?

**Comment by Sungjun4** [comment]
It is OK with 1.76.0 but error from the 1.77.0

**Comment by barendgehrels** [comment]
Closing as not a bug, and no response
