### ISSUE TITLE
Cannot make 'point_on_surface' compile

### ISSUE THREAD

**Issue by JD31** [boostorg/geometry#1278]
I don't manage to use 'point_on_surface'. (Maybe I don't use the right method??)   

``` 
    typedef boost::geometry::model::point<double, 2, boost::geometry::cs::cartesian> BGPoint;
    boost::geometry::model::polygon<BGPoint> poly;

    // ...

    BGPoint point;
    boost::geometry::point_on_surface(poly, point);
```

It does not build due to a static assert :

> In template: static assertion failed due to requirement 'boost::geometry::detail::static_assert_check<false, boost::geometry::cartesian_tag>::value': Not implemented for this type.  

> in instantiation of template class 'boost::geometry::strategy::side::services::default_strategy<boost::geometry::cartesian_tag>' requested here in instantiation of function template specialization 'boost::geometry::point_on_surface<boost::geometry::model::polygon<boost::geometry::model::point<double, 2, boost::geometry::cs::cartesian>>, boost::geometry::model::point<double, 2, ...

**Comment by vissarion** [comment]
Sorry, I cannot reproduce it. Could you please provide more information? That is, all the code you tried to compile. For example what headers are you including?

**Comment by JD31** [comment]
Here is a Goldbolt link to an example that does not compile and with all the includes I use (lot are not necessary but it is representative of my build context):
https://godbolt.org/z/PK86ocnbc

**Comment by vissarion** [comment]
You have to include also 
```
#include <boost/geometry/strategies/strategies.hpp>
```

alternatively replace all boost geometry includes by `#include <boost/geometry.hpp>`.

**Comment by JD31** [comment]
Right. Thank you.
