### ISSUE TITLE
Test libraries and executables should be declared EXCLUDE_FROM_ALL

### ISSUE THREAD

**Issue by pdimov** [boostorg/geometry#1282]
The Boost convention is that `cmake --build .` only builds the libraries. Test libraries and executables are built with `cmake --build . --target tests`.

**Comment by barendgehrels** [comment]
@vissarion I think this is handled now by one of your last PR's?

**Comment by vfisikop** [comment]
> @vissarion I think this is handled now by one of your last PR's?

Yes, https://github.com/boostorg/geometry/pull/1302 which is waiting a review feedback. Upon merging this issue will be closed automatically.

**Comment by vissarion** [comment]
> @vissarion I think this is handled now by one of your last PR's?

Yes, https://github.com/boostorg/geometry/pull/1302 which is waiting a review feedback. Upon merging this issue will be closed automatically.
