### ISSUE TITLE
Mac  M3.  boost 1.86.0  compile error 

### ISSUE THREAD

**Issue by guangbinl** [boostorg/geometry#1308]
I use the boost header library in an Unreal Engine 5.4 C++ project on a Mac M3 computer, and a syntax error is prompted during the compilation process. How can I solve this problem?  The error content is as follows：

0>is_backend.hpp(39,40): Error  : statement expression not allowed at file scope
0>   static constexpr bool value = sizeof(check(get())) == sizeof(double);
0>                                       ^
0>is_backend.hpp(39,26): Error  : constexpr variable 'value' must be initialized by a constant expression
0>   static constexpr bool value = sizeof(check(get())) == sizeof(double);

**Comment by barendgehrels** [comment]
The file `is_backend.hpp` is part of Boost.Multiprecision and not of Boost.Geometry

So you can open an issue there (AFAIK you cannot move issues from sublib to sublib).
https://github.com/boostorg/multiprecision/issues

Boost.Geometry has currently a hard dependency on Boost.Multiprecision (I think we should change that, @vissarion ? It should be somehow only be triggered if Boost.Multiprecision is to be used. It's now even in `boost/geometry/core/coordinate_promotion.hpp`, I was not aware of that or had forgotten it)

**Comment by guangbinl** [comment]
OK, I thought it was a problem with the geometry module, so I submitted it here. I will adjust the location of the problem. Thank you for your reply.
