### ISSUE TITLE
looking for extensions compatible with version in boost 1.61.0

### ISSUE THREAD

**Issue by georgevanvenrooij** [boostorg/geometry#361]
Hi,

  I recently upgraded Boost to 1.61.0 and since my software uses some extensions, I came here looking for the matching set of extension files. For Boost 1.60.0 there was a develop-1.60.0 branch but this branch seems missing for Boost 1.61.0. Could you please point me to where I can find the correct set of extension files?

**Comment by awulkiew** [comment]
You have to do some legwork for that unfortunately, i.e. find the latest commit in boost-1.61.0 tag:
https://github.com/boostorg/geometry/commits/boost-1.61.0
which is:
https://github.com/boostorg/geometry/commit/4883808e589a04882aeacb3c1d8d7a34fb9d69c7
and use its SHA to get the tree:
https://github.com/boostorg/geometry/tree/4883808e589a04882aeacb3c1d8d7a34fb9d69c7
Here are the extensions:
https://github.com/boostorg/geometry/tree/4883808e589a04882aeacb3c1d8d7a34fb9d69c7/include/boost/geometry/extensions

**Comment by georgevanvenrooij** [comment]
I tried this approach but when attempting to use the "dissolve" method, I got compile errors. I tried compiling my existing code based on the Boost 1.60.0 version of geometry and its extensions (from develop 1.60.0) with Boost 1.61.0 and each version of extensions since then and all of them fail to compile, unfortunately. I'm working on Windows 7 64-bit using VS2015 and compiling x64 code.

**Comment by awulkiew** [comment]
It's possible that there is a bug in the extensions. In the history of dissolve.hpp:

https://github.com/boostorg/geometry/commits/develop/include/boost/geometry/extensions/algorithms/dissolve.hpp

there is a fix for dissolve some time after 1.61 was released:

https://github.com/boostorg/geometry/commit/ae2a127e9169c513fd0c8e973c1297dc6452bc52

So it's possible that if you used this state of extensions it'd work for you.
