### ISSUE TITLE
rtree: order of includes matters

### ISSUE THREAD

**Issue by daniel-j-h** [boostorg/geometry#363]
I'm currently testing the new Boost 1.62 Beta1 release. Including the rtree header before the parameters header works fine. For the other way around I get errors; here's the first one:

```
include/boost/geometry/index/parameters.hpp:76:26: error: expected identifier before ‘(’ token
```

Small self-contained test case:

``` cpp
#include <boost/geometry/index/parameters.hpp>
#include <boost/geometry/index/rtree.hpp>

int main() {}
```

Found this since I'm using `clang-format` and recent versions re-order includes alphabetically.

**Comment by awulkiew** [comment]
Thanks!
Fix: https://github.com/boostorg/geometry/commit/b8b1cc5c6b084671aa8d1bfbedd4a4668b56acd4
