### ISSUE TITLE
Make Point, Box and Segment etc. hashable

### ISSUE THREAD

**Issue by cirosantilli** [boostorg/geometry#374]
For insertion into unordered sets / maps.

Possibly using `boost::hash_combine`.

Any reason not to?

**Comment by awulkiew** [comment]
Typically one would like to perform spatial, knn, skyline, ray etc. query on a collection of geometries, so a query "geometrical" in nature. I'm not sure if it would have sense to search for geometries having exactly the coordinates you're looking for. For example, two Points are considered spatially equal if their coordinates are "close enough" to each other (wrt some epsilon, at least when the coordinates are floating point numbers). If they were stored in unordered set you'd be able to find only points having exactly the same coordinates. There could be other points spatially equal to them in the container but their corresponding hash values would be dfferent.

Maybe with integer coordinates it'd have more sense but in general case I don't see a reason. Do you have some specific use case in mind?

**Comment by cirosantilli** [comment]
l don't have a real world use case right now, I was just trying to do some unit tests to learn the API, and since I don't know in which order rtree query results will come out, I wanted to write:

    assert(unordered_set(query results) == unordered_set({ expected }))
