### ISSUE TITLE
What is "QPoint::double" in doc/example_adapting_a_legacy_geometry_object_model.qbk ?

### ISSUE THREAD

**Issue by cirosantilli** [boostorg/geometry#376]
https://github.com/boostorg/geometry/blob/14d9d32d04349a518e3ac0dd237a2a81f6eceaa9/doc/example_adapting_a_legacy_geometry_object_model.qbk#L125

In particular, fails to compile with the definition: https://github.com/boostorg/geometry/blob/14d9d32d04349a518e3ac0dd237a2a81f6eceaa9/doc/example_adapting_a_legacy_geometry_object_model.qbk#L17

Removing the `QPoint::` part works.

Sorry if a C++ / library feature that Google could not explain to me.

**Comment by awulkiew** [comment]
Yes, it's probably a mistake in the example. I guess that original author at the beginning defined some coordinate type typedef in QPoint and at some point automatically changed the name to double. I'll fix it, thanks!

**Comment by mloskot** [comment]
For the record, I guess here is the original `QPoint` adoption:
https://gist.github.com/anonymous/1798839 (with variant here https://gist.github.com/meastp/1852693)
developed by @meastp  as part of this thread
http://boost-geometry.203548.n3.nabble.com/Using-Boost-Geometry-with-a-legacy-class-hierarchy-td3734832.html

That initial version includes

```
template<> struct coordinate_type<QPoint>
{ typedef double type; };
```

**Comment by meastp** [comment]
@cirosantilli, @awulkiew : It is a typo, and should be just double instead of QPoint::double. :)
