### ISSUE TITLE
Polygon validation

### ISSUE THREAD

**Issue by Ironholds** [boostorg/geometry#377]
boost::geometry's WKT-reading code accepts "POLYGON((2 1.3,2.4 1.7))" as a valid WKT string - and it is a valid *string* but is not a valid *polygon*, since polygons have to be closed objects under the WKT spec. Is there any way to have the code validate the polygons more strictly, either in WKT-reading or generally?

**Comment by Ironholds** [comment]
Nada?

**Comment by barendgehrels** [comment]
boost::geometry::is_valid checks validity of a polygon (if they are closed - and more).

**Comment by Ironholds** [comment]
Wonderful; thanks so much!
