### ISSUE TITLE
point within box not behaving as expected

### ISSUE THREAD

**Issue by agauniyal** [boostorg/geometry#390]
Pardon me if I'm wrong, but why would such an example give result as '_no_'

```cpp
#include <iostream>
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/register/point.hpp>
#include <boost/geometry/geometries/register/box.hpp>

struct my_point
{
    double x, y;
	my_point(double _x, double _y) : x(_x), y(_y) {}
};

struct my_box
{
    my_point ll, ur;
    my_box(double x1, double y1, double x2, double y2) : ll(x1,y1), ur(x2,y2) {}
};

// Register the point type
BOOST_GEOMETRY_REGISTER_POINT_2D(my_point, double, cs::cartesian, x, y)

// Register the box type, also notifying that it is based on "my_point"
BOOST_GEOMETRY_REGISTER_BOX(my_box, my_point, ll, ur)

int main()
{
    my_box b(2,1,3,4);
    my_point p(2.0,2.0);
	std::cout << "within: " << (boost::geometry::within(p, b) ? "yes" : "no") << std::endl;
    return 0;
}
```

I tried to draw a rectangle on paper and the point fell inside it. I'm sure there is something wrong with my approach here, is that `box b` not qualified to be a box? Or is it something else?

**Comment by awulkiew** [comment]
This is how `within` predicate is defined [1][2]. `Within` return sture only if the first geometry overlaps the interior of the second geometry. Use `covered_by` instead.

[1] https://en.wikipedia.org/wiki/DE-9IM
[2] http://www.opengeospatial.org/standards/sfa

**Comment by agauniyal** [comment]
seems about right!
