### ISSUE TITLE
Some problem in Generating and Improving Documentation

### ISSUE THREAD

**Issue by Rylynnn** [boostorg/geometry#414]
Here is a little problem in Generating and Improving Documentation.

The path when I followed the step compiling doxygen_xml2qbk tool, the path of the following call does not
work.
```
./b2 libs/geometry/src/docutils/tools/doxygen_xml2qbk
```
So, I searched the folder and found the right path is:
```
./b2 libs/geometry/doc/src/docutils/tools/doxygen_xml2qbk
```

Could you please check this problem, or this problem happened only on my linux?

**Comment by Rylynnn** [comment]
@awulkiew

**Comment by mloskot** [comment]
@Rylynnn 
>  I followed the step compiling doxygen_xml2qbk tool

Do you refer to the [doc/readme.txt](https://github.com/boostorg/geometry/blob/develop/doc/readme.txt) instructions? where they say this?

> 3) run b2 in src/docutils/tools/doxygen_xml2qbk to build doxygen_xml2qbk executable

**Comment by awulkiew** [comment]
@Rylynnn ok thanks I'll fix it.

@mloskot no, about Wiki: https://github.com/boostorg/geometry/wiki/Generating-and-Improving-Documentation

**Comment by awulkiew** [comment]
@Rylynnn also section **Building documentation** is outdated because instead of running `make_qbk.py` one should now run `b2` (`../../../b2`) from `doc` directory.

Were you able to build the docs?

**Comment by Rylynnn** [comment]
@awulkiew no, i won't able to build the docs yesterday, and I did not find the solution, so I did not put this bug to you.
But I follow the new step now, and it works, but in my local terminal, it failed updating 1 target, the whole report is [here](https://gist.github.com/Rylynnn/d58bf3221eb72e6631d128c7dabdc534).

**Comment by awulkiew** [comment]
> Make sure that you can call all of the above programs from any directory, including doxygen_xml2qbk and b2. If needed add Boost root directory and BOOST_ROOT/dist/bin to PATH.

Have you done that?

**Comment by Rylynnn** [comment]
It works! :)Thank a lot!

**Comment by awulkiew** [comment]
I'm glad it works. Closing.
