### ISSUE TITLE
Failures on Appveyor

### ISSUE THREAD

**Issue by pdimov** [boostorg/geometry#430]
While watching the superproject Appveyor, I notice that this `geometry` commit:

https://ci.appveyor.com/project/boostorg/boost/build/1.0.4441-develop

passes the tests, but the two subsequent ones:

https://ci.appveyor.com/project/boostorg/boost/build/1.0.4442-develop
https://ci.appveyor.com/project/boostorg/boost/build/1.0.4443-develop

fail (on all three versions being tested - msvc-12.0, msvc-14.0, msvc-14.1.)

**Comment by awulkiew** [comment]
Thanks about the info. The PR fixing it is ready: https://github.com/boostorg/geometry/pull/429

**Comment by pdimov** [comment]
You're way ahead of me then. :-)
