### ISSUE TITLE
Jak dodać dwa wieloboki zamknięte (svg path) do siebie? 

### ISSUE THREAD

**Issue by xor256** [boostorg/geometry#446]
Polygon=Łamana zamknięta składa się nie tylko z punktów, ale i z odcinków beziera.

**Comment by xor256** [comment]
How to add two closed polygons (svg path) to each other? (tłumaczenie z google translate)

**Comment by awulkiew** [comment]
Bezier segments are not supported. What you can do now depends what you're trying to do exactly. You could find a different library supporting bezier segments. You could also convert each bezier segment to some number of linear segments (based on required precision). Then this geometry could be represented as Boost.Geometry Polygon and then you could calculate a union (see example here: http://www.boost.org/doc/libs/1_66_0/libs/geometry/doc/html/geometry/reference/algorithms/union_/union__3.html). However in Boost.Geometry there is no algorithm converting bezier curve to some number of linear segments (a Linestring) so you'd still have to find a different library for that or write your own algorithm.
