### ISSUE TITLE
when will dissolve feature be merged to master?

### ISSUE THREAD

**Issue by huangynn** [boostorg/geometry#447]
as title, just  wondering that

**Comment by barendgehrels** [comment]
Good point, I will come back to this. There are recent changes in dissolve (so, in develop branch indeed), and there will be some more.

**Comment by awulkiew** [comment]
So I guess the answer is we're not sure but we plan to do it in the near future. In any case you'll find the info in the release notes. I'll close the issue, if needed reopen it.

**Comment by systemed** [comment]
Just a +1 to this - I use Boost.Geometry as the core of https://github.com/systemed/tilemaker and have been encountering issues when simplifying multipolygons creates invalid geometries. Being able to fix this with dissolve would be a great boon. Thanks for an excellent library as always.
