### ISSUE TITLE
Adaptor for C++11 std::tuple needed?

### ISSUE THREAD

**Issue by norbertwenzel** [boostorg/geometry#458]
Do you see any value in also adapting `std::tuple` the same as Boost.Tuple? This seems to be the only currently adapted Boost type, that has a C++11 `std::` version and is not readily available for use in Geometry.

If there is any interest I'd be willing to do that now, as I have the environment to build the lib and documentation currently set up.

**Comment by awulkiew** [comment]
I personally don't need it but I'm fine with adding it even if it's only for completeness.
