### ISSUE TITLE
clang 5.0 error

### ISSUE THREAD

**Issue by skn123** [boostorg/geometry#459]
``/usr/local/include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp:188:61: error: 
      no member named 'to_address' in
      'boost::pointer_traits<boost::variant<boost::geometry::index::detail::rtree::variant_leaf<std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> >,
      boost::geometry::index::quadratic<4, 2>,
      boost::geometry::model::box<boost::geometry::model::point<float, 2,
      boost::geometry::cs::cartesian> >,
      boost::geometry::index::detail::rtree::allocators<std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> > >,
      std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> >,
      boost::geometry::index::quadratic<4, 2>,
      boost::geometry::model::box<boost::geometry::model::point<float, 2,
      boost::geometry::cs::cartesian> >,
      boost::geometry::index::detail::rtree::node_variant_static_tag>,
      boost::geometry::index::detail::rtree::node_variant_static_tag>,
      boost::geometry::index::detail::rtree::variant_internal_node<std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> >,
      boost::geometry::index::quadratic<4, 2>,
      boost::geometry::model::box<boost::geometry::model::point<float, 2,
      boost::geometry::cs::cartesian> >,
      boost::geometry::index::detail::rtree::allocators<std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> > >,
      std::pair<boost::geometry::model::box<boost::geometry::model::point<float,
      2, boost::geometry::cs::cartesian> >, std::pair<double, double> >,
      boost::geometry::index::quadratic<4, 2>,
      boost::geometry::model::box<boost::geometry::model::point<float, 2,
      boost::geometry::cs::cartesian> >,
      boost::geometry::index::detail::rtree::node_variant_static_tag>,
      boost::geometry::index::detail::rtree::node_variant_static_tag> > *>'
        Al::construct(alloc_node, boost::pointer_traits<P>::to_address(p...
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^
``

**Comment by awulkiew** [comment]
Which version? Master branch maybe?

**Comment by awulkiew** [comment]
I'm assuming it's master branch. Should be fixed now.
