### ISSUE TITLE
Divide by zero in sjoberg_intersection.hpp

### ISSUE THREAD

**Issue by springmeyer** [boostorg/geometry#507]
Running the tests with after compiling with `-fsanitize=undefined` reveals a divide by zero bug:

```
../../boost/geometry/formulas/sjoberg_intersection.hpp:1200:41: runtime error: division by zero
    #0 0x10f9fb342 in boost::geometry::formula::sjoberg_intersection<double, boost::geometry::strategy::vincenty::inverse, 4u>::calc_ts(double const&, double const&, boost::geometry::formula::sjoberg_geodesic<double, 4u> const&, boost::geometry::formula::sjoberg_geodesic<double, 4u> const&, double&, double&) (/Users/danespringmeyer/projects/boost/libs/geometry/../../bin.v2/libs/geometry/test/strategies/strategies_segment_intersection_geo.test/clang-darwin-5.0/debug/strategies_segment_intersection_geo:x86_64+0x1008b1342)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../boost/geometry/formulas/sjoberg_intersection.hpp:1200:41 in 
```

Note:

 - `boost::geometry` is compiled like: https://gist.github.com/springmeyer/0039d329df5cb8e040c0ee0284267457
 - I presume that this divide by zero could result in `SIGFPE` if the coordinate type were floating point

**Comment by awulkiew** [comment]
Thanks. Is my understanding correct that it's not that the division occured during the tests but the UBSan detects a potential for it? AFAIR at this point it is guaranteed that the division by 0 will not occur due to the previous checks. I have to check this again though to be sure.

**Comment by springmeyer** [comment]
> Is my understanding correct that it's not that the division occured during the tests but the UBSan detects a potential for it?

No, ubsan detects only actual occurrences. It does not, to my knowledge, have the ability to statically analyze. It is fully dependent on actual test data and actual code paths executed to detect problems.

**Comment by awulkiew** [comment]
Fixed. Thanks.

**Comment by springmeyer** [comment]
Thanks @awulkiew. I was curious what the actual fix was, so I looked back in the recent commits and found https://github.com/boostorg/geometry/commit/ece82259a166c3d9a501df4e5e6010fa7bfe32a5. That is it, correct?

**Comment by awulkiew** [comment]
Yes. There is a related issue, i.e. the algorithm shouldn't even go into this function because correct result should be calculated using newton method before. But this is another fix for another time.
