### ISSUE TITLE
R tree query hundreds of points which satisfy a condition

### ISSUE THREAD

**Issue by dayexingyang** [boostorg/geometry#509]
I want to query the points of which distances between a line are less than a value( such as 2.0). But there are hundreds of candidate points. So I want to speed up the query with R tree.  I'm not sure if r tree can handle it and how to set it up. Could you provide some advices?
Thank you!

**Comment by awulkiew** [comment]
Hi, so this would be a spatial query with line+distance defining area. You could create buffer/polygon of this line and pass it into spatial query but this would not be optimal. It would be better to pass some object holding a line and your distance into `bgi::intersects()`. When this predicate is passed into the `query()` internally `bg::intersects()` is called. So you'd need to overload this function 2 times. One for your line/area type and Box and second one for line/area type and Point. Internally you would call: `bg::distance(line, value) < distance`.

**Comment by awulkiew** [comment]
Actually you'd probably need only one overload, since one type would be your line/area type, the other one some generic Point or Box and `bg::distance()` should work for both combinations.

**Comment by awulkiew** [comment]
See here: https://stackoverflow.com/questions/19490435/boost-geometry-spatial-query-shapes
