### ISSUE TITLE
Minor documentation error matrix_transformers

### ISSUE THREAD

**Issue by Multimath** [boostorg/geometry#558]
There are minor problems with the language of the documentation in 

 geometry/include/boost/geometry/strategies/transform/matrix_transformers.hpp 

I propose the following fixes:

[matrix_transformers.hpp.patch.txt](https://github.com/boostorg/geometry/files/2889342/matrix_transformers.hpp.patch.txt)

**Comment by vissarion** [comment]
Thanks for the report. Do you want to give it a try and propose a PR?

**Comment by awulkiew** [comment]
Thanks! Fixed in: https://github.com/boostorg/geometry/commit/d6bafb9908abe7d1507ab6f02ed7a3a39e21fee6
