### ISSUE TITLE
VC++ error C4458: declaration of 'debug_phase' hides class member

### ISSUE THREAD

**Issue by vschoech** [boostorg/geometry#597]
I am using Microsoft Visual Studio 15.8.0 (VCToolsVersion 14.15.26726) to compile boost 1.70.0. I use compiler flag /W4. The following error occurs in geometry:

> \boost_1_70_0\boost\geometry\algorithms\detail\is_valid\multipolygon.hpp(284): error C4458: declaration of 'debug_phase' hides class member

See also:
https://svn.boost.org/trac10/ticket/13377

**Comment by barendgehrels** [comment]
Thanks for the report Volker, fixed in 1.71

**Comment by barendgehrels** [comment]
Also this issue is now fixed and merged, will close it. Thanks for the heads up and your patience.

**Comment by vschoech** [comment]
I can confirm that as of boost 1.72.0 this is no longer reproducible in our code.
