### ISSUE TITLE
VC++ warning C4127: conditional expression is constant

### ISSUE THREAD

**Issue by vschoech** [boostorg/geometry#599]
I am using Microsoft Visual Studio 15.8.0 (VCToolsVersion 14.15.26726) to compile boost 1.70.0. I use compiler flag /W4. The following warning occurs in geometry:

> \boost_1_70_0\boost\geometry\algorithms\detail\overlay\sort_by_side.hpp(372): warning C4127: conditional expression is constant

See also:
https://svn.boost.org/trac10/ticket/13596

**Comment by barendgehrels** [comment]
Thanks Volker, this one is also fixed, sorry for the delay. Target is 1.71

**Comment by barendgehrels** [comment]
This one is also fixed and merged, will close it. Thanks for the heads up and your patience.

**Comment by vschoech** [comment]
I can confirm that this issue is not reproducible in boost 1.72.0.
