### ISSUE TITLE
VC++ warning C4456: declaration of 'prev' hides previous local declaration

### ISSUE THREAD

**Issue by vschoech** [boostorg/geometry#600]
I am using Microsoft Visual Studio 15.8.0 (VCToolsVersion 14.15.26726) to compile boost 1.70.0. I use compiler flag /W4. The following warning occurs in geometry:

> \boost_1_70_0\boost\geometry\algorithms\detail\is_valid\has_spikes.hpp(149): warning C4456: declaration of 'prev' hides previous local declaration

See also:
https://svn.boost.org/trac10/ticket/13598

**Comment by barendgehrels** [comment]
Thanks Volker, this one is fixed now, sorry for the delay. Target is 1.71

**Comment by barendgehrels** [comment]
It is fixed and merged, will close it. Thanks for the heads up and your patience.

**Comment by vschoech** [comment]
I can confirm that as of boost 1.72.0 this is no longer reproducible in our code.
