### ISSUE TITLE
Clang warning: Implicit conversion loses integer precision: 'const coordinate_type' (aka 'const long long') to 'const typename coordinate_type<rect<int> >::type' (aka 'const int')

### ISSUE THREAD

**Issue by vschoech** [boostorg/geometry#601]
I'm using Apple LLVM version 10.0.0 to compile boost 1.70.0. The following warning (which we declared an error for our project) occurs in geometry:

> /boost_1_70_0/boost/geometry/strategies/cartesian/expand_point.hpp:66:45: Implicit conversion loses integer precision: 'const coordinate_type' (aka 'const long long') to 'const typename coordinate_type<rect<int> >::type' (aka 'const int')

See also:
https://svn.boost.org/trac10/ticket/13604

#598

**Comment by barendgehrels** [comment]
Hi @vschoech , this warning on itself is fine and should be there.
The question is where it comes from. It can either (1) come from inside our library (I assume that), or (2) you call some function with different types and it comes from there.

I did some checks for (1) and in my checks the local types there all match the input types.
I tried to check (2) but any overlay does not support (yet) different coordinate types, there is a static assertion for that. But maybe you don't apply it with an overlay.

Do you have minimal code to reproduce this warning?

**Comment by barendgehrels** [comment]
Closed #598 as duplicate with this one, and also the trac one, conform description above

**Comment by vschoech** [comment]
> Hi @vschoech , this warning on itself is fine and should be there.
> The question is where it comes from. It can either (1) come from inside our library (I assume that), or (2) you call some function with different types and it comes from there.

Hi @barendgehrels , I can now confirm that we are indeed calling some function with different types, i.e., the problem is rooted in our own code and must be fixed on our end. Thank you very much for looking into it on your end. I apologize for the false alarm! *blush*

**Comment by barendgehrels** [comment]
@vschoech  Hi Volker, OK, no problem, I'm glad it could be closed now.
