### ISSUE TITLE
for_each_segment leads to infinite loop on empty ring

### ISSUE THREAD

**Issue by henzim** [boostorg/geometry#624]
I wanted to use  `for_each_segment` in a simple (DXF) drawing function for polygons. 
The function should loop over all segments of the outer ring and inner rings and draw them

It seems that for_each_segment does not work as (I) expected, when used on rings. Empty rings lead to inifinte loop (and crashes if one tries to access the first or second point of the respective segment)

https://wandbox.org/permlink/Y7YrBgAcCHOYy4Zu

**Comment by mloskot** [comment]
Could you see if #625 fixes the problem?

p.s. Please, always state version of Boost (Boost.Geometry) explicitly in the issue description (not indirectly, asking to fish for it on an external linked page like `-I/opt/wandbox/boost-1.71.0/gcc-head/include` on the wandbox.
