### ISSUE TITLE
Proposal: Include example code for arithmetic operations in the documentation

### ISSUE THREAD

**Issue by spacewafer** [boostorg/geometry#658]
The arithmetic functions like the dot_product and cross_product don't have examples specified in their respective documentation pages. I have made some examples ready for it. Should I add it?

**Comment by mloskot** [comment]
AFAIS, none of the arithmetic operations display any exampleshttps://www.boost.org/doc/libs/1_72_0/libs/geometry/doc/html/geometry/reference/arithmetic.html
or, you'd have to provide links to pages you are talking about.

However, I'd simply submit PR, then it will be possible to see what examples you are proposing, review them and accept. IMHO, documentation with examples is always appreciated by readers.
