### ISSUE TITLE
Incorrect result of area calculated for polygon

### ISSUE THREAD

**Issue by linshu77** [boostorg/geometry#662]
Here is my code：	

```
typedef bg::model::d2::point_xy<double> DPoint;
typedef bg::model::polygon<DPoint, false> DPolygon;
typedef bg::model::multi_polygon<DPolygon> MPolygon;
DPolygon poly1;
DPolygon poly2;
MPolygon poly;
auto lstOf = boost::assign::list_of
    (DPoint(171.60480351137778, 162.32096650635697))
    (DPoint(172.21795926332567, 162.99736073096460))
    (DPoint(172.21795926332567, 170.00000000000000))
    (DPoint(171.60480351137778, 170.00000000000000))
    (DPoint(171.60480351137778, 162.32096650635697));
poly1.outer().assign(lstOf.begin(), lstOf.end());
lstOf = boost::assign::list_of
    (DPoint(200.00000000000000, 166.00002000000001))
    (DPoint(184.00004999999999, 166.00002000000001))
    (DPoint(180.00004999999999, 164.00002000000001))
    (DPoint(169.99998889000000, 162.00000277999999))
    (DPoint(182.00000000000000, 159.00000000000000))
    (DPoint(200.00000000000000, 159.00000000000000))
    (DPoint(200.00000000000000, 166.00002000000001));
poly2.outer().assign(lstOf.begin(), lstOf.end());
bg::correct(poly1);
bg::correct(poly2);
bg::intersection(poly1, poly2, poly);
double Area = bg::area(poly);
```

The "Area" should be 0, but the result is 4.5. Why?It should be a mistake.

-----

@linshu77 Please, learn how to format GitHub issues. I also corrected the issue subject.

**Comment by barendgehrels** [comment]
Can you please try to compile the code with the define `BOOST_GEOMETRY_NO_ROBUSTNESS`?
This will be the default in one of the future versions.

**Comment by linshu77** [comment]
This is my code，It can be compiled by DEV-C + + 5.11.

#include <iostream>
#include <cstdio>
#include <boost/assign.hpp>
#include <boost/assign/list_of.hpp>
#include <boost/geometry/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>
using namespace std;
namespace bg = boost::geometry;
int main()
{
	typedef bg::model::d2::point_xy<double> DPoint;
	typedef bg::model::polygon<DPoint, false> DPolygon;
	typedef bg::model::multi_polygon<DPolygon> MPolygon;
	DPolygon poly1;
	DPolygon poly2;
	MPolygon poly;
	std::list<DPoint> lstOf = boost::assign::list_of
	    (DPoint(171.60480351137778, 162.32096650635697))
	    (DPoint(172.21795926332567, 162.99736073096460))
	    (DPoint(172.21795926332567, 170.00000000000000))
	    (DPoint(171.60480351137778, 170.00000000000000))
	    (DPoint(171.60480351137778, 162.32096650635697));
	poly1.outer().assign(lstOf.begin(), lstOf.end());
	lstOf = boost::assign::list_of
	    (DPoint(200.00000000000000, 166.00002000000001))
	    (DPoint(184.00004999999999, 166.00002000000001))
	    (DPoint(180.00004999999999, 164.00002000000001))
	    (DPoint(169.99998889000000, 162.00000277999999))
	    (DPoint(182.00000000000000, 159.00000000000000))
	    (DPoint(200.00000000000000, 159.00000000000000))
	    (DPoint(200.00000000000000, 166.00002000000001));
	poly2.outer().assign(lstOf.begin(), lstOf.end());
	bg::correct(poly1);
	bg::correct(poly2);
	bg::intersection(poly1, poly2, poly);
	double Area = bg::area(poly);
	cout<<Area;
	return 1;
}

**Comment by barendgehrels** [comment]
Thanks for the code - but that was actually not my question...

**Comment by mloskot** [comment]
@linshu77 Please, once again, check https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax to learn how to format code blocks

**Comment by linshu77** [comment]
@mloskot Sorry, this is my first issue.

**Comment by linshu77** [comment]
When I change the data order, I will get the right result. why?

```
#include <iostream>
#include <boost/assign.hpp>
#include <boost/assign/list_of.hpp>
#include <boost/geometry/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>
using namespace std;
namespace bg = boost::geometry;
int main()
{
	typedef bg::model::d2::point_xy<double> DPoint;
	typedef bg::model::polygon<DPoint, false> DPolygon;
	typedef bg::model::multi_polygon<DPolygon> MPolygon;
	DPolygon poly1;
	DPolygon poly2;
	MPolygon poly;
	std::list<DPoint> lstOf = boost::assign::list_of
	    (DPoint(171.60480351137778, 170.00000000000000))
	    (DPoint(171.60480351137778, 162.32096650635697))
	    (DPoint(172.21795926332567, 162.99736073096460))
	    (DPoint(172.21795926332567, 170.00000000000000))
	    (DPoint(171.60480351137778, 170.00000000000000));
	poly1.outer().assign(lstOf.begin(), lstOf.end());
	lstOf = boost::assign::list_of
	    (DPoint(200.00000000000000, 166.00002000000001))
	    (DPoint(184.00004999999999, 166.00002000000001))
	    (DPoint(180.00004999999999, 164.00002000000001))
	    (DPoint(169.99998889000000, 162.00000277999999))
	    (DPoint(182.00000000000000, 159.00000000000000))
	    (DPoint(200.00000000000000, 159.00000000000000))
	    (DPoint(200.00000000000000, 166.00002000000001));
	poly2.outer().assign(lstOf.begin(), lstOf.end());
	bg::correct(poly1);
	bg::correct(poly2);
	bg::intersection(poly1, poly2, poly);
	double Area = bg::area(poly);
	cout<<Area;
	return 1;
}
```

**Comment by mloskot** [comment]
@linshu77 Can you run the test that @barendgehrels requested in his earlier comment?

Simply, add the `#define BOOST_GEOMETRY_NO_ROBUSTNESS` at the top of your `.cpp` file like so

```cpp
#define BOOST_GEOMETRY_NO_ROBUSTNESS
#include <iostream>
#include <boost/assign.hpp>
#include <boost/assign/list_of.hpp>
#include <boost/geometry/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>
using namespace std;
namespace bg = boost::geometry;
int main()
{
...
}
```

build and run it.

**Comment by linshu77** [comment]
Thank you，add the ` #define BOOST_GEOMETRY_NO_ROBUSTNESS` , It will get the right results.

**Comment by barendgehrels** [comment]
@linshu77 : Thanks for testing and good to hear it solves the problem.
@mloskot  : Thanks for your assistence
