### ISSUE TITLE
Add unit tests for geometry models

### ISSUE THREAD

**Issue by mloskot** [boostorg/geometry#673]
This task is about adding new tests for basic classes like geometry models (e.g. `point`, `point_xy`, etc.) to exercise their basic operations.

Although we can be fairly sure most, if not all, are covered by the extensive tests of algorithms, there is a value of having separate unit tests for each of the models. Such tests clearly show (document!) what operations are actually tested. Not something that can be easily displayed from all the complex tests, unless one knows what to `grep` through the code for.

A good place to start is to look at and follow the unit test for `box` in [test/geometries/box.cpp](https://github.com/boostorg/geometry/blob/develop/test/geometries/box.cpp).

### References

Covering basic classes like geometry models with unit tests have been discussed here
https://github.com/boostorg/geometry/pull/671#issuecomment-593110240

**Comment by sudo-panda** [comment]
Is someone working on this or can I do it?

**Comment by mloskot** [comment]
@sudo-panda I'm not aware of anyone working on it. Only @digu-007  mentioned  https://github.com/boostorg/geometry/pull/671#issuecomment-593085813 adding test for `point_xy`.

**Comment by digu-007** [comment]
> @sudo-panda I'm not aware of anyone working on it. Only @digu-007 mentioned [#671 (comment)](https://github.com/boostorg/geometry/pull/671#issuecomment-593085813) adding test for `point_xy`.

I was waiting for review in #671 and then I can send the PR for this issue as well.

**Comment by mloskot** [comment]
@digu-007  A unit-test for `point_xy` is quite an independent task from PR #671

**Comment by digu-007** [comment]
> @digu-007 A unit-test for `point_xy` is quite an independent task from PR #671

@mloskot Yes, but my re-review is about unit test of `point_xyz`. I'm waiting for approval of that part.

**Comment by mloskot** [comment]
@digu-007 That is clear. What I mean, that if you want to add unit test for `point_xy`, you can add it, as new PR, and you can add it separately from review and merge timeline of your PR.

**Comment by digu-007** [comment]
@mloskot Ok I'll send a PR tomorrow only, starting with `point_xy` and then I can work on the remaining models as well.
