### ISSUE TITLE
Complexity for intersection

### ISSUE THREAD

**Issue by rconde01** [boostorg/geometry#691]
The complexity for intersection is not available in the documentation.

https://www.boost.org/doc/libs/1_72_0/libs/geometry/doc/html/geometry/reference/algorithms/intersection/intersection_3.html

Is it located somewhere else? Or is it known but not documented?

**Comment by awulkiew** [comment]
No it is not. Internally we use space partitioning similar to kd-tree and sorting intersection points by the position on geometry so the average complexity is something around linearitmic in terms of number of segments in geometries and number of intersections found. It of course depends on the data as in all cases when space partitioning is involved,
