### ISSUE TITLE
Including boost/geometry/index/parameters.hpp directly causes a compile error

### ISSUE THREAD

**Issue by rconde01** [boostorg/geometry#725]
#include <boost/geometry/index/parameters.hpp>

https://godbolt.org/z/ebxrBQ

`In file included from <source>:1:

/celibs/boost_1_73_0/boost/geometry/index/parameters.hpp:292:13: error: unknown type name 'default_strategy'
    typedef default_strategy type;
/celibs/boost_1_73_0/boost/geometry/index/parameters.hpp:293:13: error: unknown type name 'default_strategy'
    typedef default_strategy result_type;
/celibs/boost_1_73_0/boost/geometry/index/parameters.hpp:307:19: error: unknown type name 'default_strategy'
    static inline default_strategy apply(Parameters const&)
/celibs/boost_1_73_0/boost/geometry/index/parameters.hpp:309:16: error: use of undeclared identifier 'default_strategy'
        return default_strategy();`

**Comment by vissarion** [comment]
It is not clear why you want to include only parameters, but a workaround could be to add
```#include <boost/geometry/strategies/default_strategy.hpp>```
before your include.

**Comment by vissarion** [comment]
Moreover, this is a general issue of the library, see https://github.com/boostorg/geometry/issues/523

**Comment by rconde01** [comment]
Yes that was my workaround. I just mentioned it because I encountered it when updating boost versions.

**Comment by rconde01** [comment]
Close as it's a dupe of #523
