### ISSUE TITLE
voronoi warning: conversion from '__int64' to 'const int' at insert(const Segment& segment, VB* vb)

### ISSUE THREAD

**Issue by yoavmil** [boostorg/geometry#731]
My datatype is int64, and for some reason Boost is converting it to int.
` struct Point { int64 X, Y; } `

> polygon\voronoi.hpp(68,8): warning C4244: 'argument': conversion from '__int64' to 'const int', possible loss of data

```c++
template <typename Segment, typename VB>
typename enable_if<
  typename gtl_if<
    typename is_segment_concept<
      typename geometry_concept<Segment>::type
    >::type
  >::type,
  std::size_t
>::type insert(const Segment& segment, VB* vb) {
  return vb->insert_segment(
      x(low(segment)), y(low(segment)), // this is where the warning comes from
      x(high(segment)), y(high(segment)));
}
```

Maybe I'm doing something wrong, please advise, and maybe it is similar to [this](https://github.com/boostorg/geometry/issues/629).

**Comment by vissarion** [comment]
@yoavmil this issue is about `polygon` library so you should probably try to open an issue there https://github.com/boostorg/polygon/issues

**Comment by yoavmil** [comment]
moved to https://github.com/boostorg/polygon/issues/46
