### ISSUE TITLE
Misspelled config macros

### ISSUE THREAD

**Issue by jefftrull** [boostorg/geometry#750]
The test `algorithms/set_operations/intersection/intersection.cpp` refers to two macros, `BOOST_NO_INT64`, and `BOOST_HAS_INT64_T`, which don't exist - probably `BOOST_NO_INT64_T` is what is meant.

**Comment by ayaankhan98** [comment]
https://github.com/boostorg/geometry/blob/5fe26e45b4c8fad04b6477f302343bb4b118c513/test/algorithms/set_operations/intersection/intersection.cpp#L958

@jefftrull  are you refering to this?
if so then  
if `BOOST_NO_INT64` and `BOOST_HAS_INT64_T`  don't exist then this code below
```C++
 #if !defined(BOOST_NO_INT64_T) || defined(BOOST_HAS_MS_INT64) 
```
is the fix?

**Comment by jefftrull** [comment]
That looks right to me!

**Comment by ashiscs** [comment]
Is this issue still open to work?

**Comment by ayaankhan98** [comment]
> Is this issue still open to work?

@ashiscs 
already there is a PR #755 which is needed to be merged

**Comment by awulkiew** [comment]
Thanks!
