### ISSUE TITLE
Internal Compiler Error with MSVC++20 and modules

### ISSUE THREAD

**Issue by myblindy** [boostorg/geometry#760]
You can clone [this repository](https://github.com/myblindy/boost_compiler_crash_repro) to reproduce it, I tried to make it as small as possible, it's just a tree query. 

If moved outside of the module, the code works correctly. Inside it just dies. 

I'm using VS 16.8 Preview 3.1, and I got installed the boost library with `vcpkg install boost-geometry:x64-windows` (the application is 64-bit).

**Comment by mloskot** [comment]
I think this report belongs to https://developercommunity.visualstudio.com

**Comment by myblindy** [comment]
I reported it [there](https://developercommunity.visualstudio.com/content/problem/1207975/internal-compiler-error-with-boost-geometry-tree-q.html) as well, you can close this if you believe C++20 modules shouldn't be supported.

**Comment by mloskot** [comment]
👍  No, it's not that C++20 modules are not supported deliberately in anyway. It's just that nobody probably has put any effort to ensure Boost.Geometry supports it well.

**Comment by barendgehrels** [comment]
Closing this issue, I don't think we can fix internal compiler errors
