### ISSUE TITLE
How to query on distance range?

### ISSUE THREAD

**Issue by cyang-kth** [boostorg/geometry#781]
I have a large set of points and I want to query a point _A_ with a distance range (min, max) to find all the points whose distance to _A_ lies in that range.

How to implement that query using the rtree index?

**Comment by awulkiew** [comment]
If you need all of the points then this would be a spatial query, not knn query. So you can pass a bounding box created for max distance and then filter the points that are closer to min or further to max:
```
rt.query(bgi::intersects(box{{a.x() - max, a.y() - max}, {a.x() + max, a.y() + max}})
      && bgi::satisfies([&](auto const& v) {
             auto const d = bg::distance(a, v);
             return d >= min && d <= max;
         }),
         std::back_inserter(result));
```

**Comment by cyang-kth** [comment]
Thanks for your reply. When both the min and max are quite big, the method based on intersection may need to examine a lot of points. I think it would be more efficient to customize the process of rtree iteration by comparing the min and max distance to a bounding box with this distance range. It seems to be define a new type of spatial predicate but I could not find any resources or example on that. 

https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/spatial_indexes/group__predicates.html

It seems that all the current predicates takes geometry as input or compare on value type, is there a way to customize the iteration process on rtree?

**Comment by awulkiew** [comment]
Currently there is no official way of defining a custom query.

If you think that min can be big and that it would be possible to prune large parts of the tree this way you can always pass a negated predicate. Unfortunately for now it is only possible to pass boxes. So instead of:
```
   bgi::intersects(box{{a.x() - max, a.y() - max}, {a.x() + max, a.y() + max}})
&& bgi::satisfies([&](auto const& v) {
       auto const d = bg::distance(a, v);
           return d >= min && d <= max;
   }
```
you can pass a square inscribed in a circle with `min` radius:
```
double m = min / sqrt(2.0);
   bgi::intersects(box{{a.x() - max, a.y() - max}, {a.x() + max, a.y() + max}})
&& ! bgi::intersects(box{{a.x() - m, a.y() - m}, {a.x() + m, a.y() + m}})
&& bgi::satisfies([&](auto const& v) {
       auto const d = bg::distance(a, v);
           return d >= min && d <= max;
   }
```

Some basic nsphere support is implemented in the extensions (https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/extensions). You need develop branch for that. If you want to play with it you have to include https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/extensions/nsphere/nsphere.hpp

And finally you could have your representation of a circle or even a ring and implement the `bg::intersection()` for boxes and points by yourself. See: https://stackoverflow.com/questions/19490435/boost-geometry-spatial-query-shapes

**Comment by cyang-kth** [comment]
```cpp
typedef boost::geometry::model::point<double, 2,
    boost::geometry::cs::cartesian> Point; // Point for rtree box
struct Ring {
  Point p;
  double r1; // inner radius
  double r2; // external radius
};
```

**Comment by cyang-kth** [comment]
https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/adapted.html

**Comment by awulkiew** [comment]
You need 2 specializations of `bg::intersects()` one for the box type used by the R-tree (`rtree<...>::bounds_type`), and the other one for the point type you store. So you also have to add:
```
template <>
inline bool intersects(Point const &p, Ring const& ring)
{...};
```
Basically look at the compiler output, see what types are passed into `bg::intersects()` and implement specializations for these types. If these function templates are instantiated then the compiler will not instantiate the default one and will not check the concepts at all.

This works for me with msvs-2017 and gcc-8.1:
```
#include <boost/geometry.hpp>
#include <vector>

namespace bg = boost::geometry;
namespace bgi = boost::geometry::index;

typedef bg::model::point<double, 2, bg::cs::cartesian> Point;
typedef bg::model::box<Point> Box;

namespace Abc {

struct Ring {
    Point p;
    double r1;
    double r2;
};

}

namespace boost { namespace geometry {
        
template <>
inline bool intersects(Box const &b, Abc::Ring const& ring)
{
    return false;
}

template <>
inline bool intersects(Point const &b, Abc::Ring const& ring)
{
    return false;
}

}}

int main()
{
    bgi::rtree<std::pair<Point, size_t>, bgi::quadratic<16>> rt;

    Abc::Ring ring;
    std::vector<std::pair<Point, size_t>> vec;
    rt.query(bgi::intersects(ring), std::back_inserter(vec));
}
```

Note that there are problems with overloads (without `template<>`) with non-msvs compilers. In this case the order of includes and definitions is important. But it seems that explicit template specializations works fine.

**Comment by cyang-kth** [comment]
@awulkiew 
Thanks for your help. I also discovered that I need to implement the intersects for both Box type and Point type against the Ring. I test on Mac and Ubuntu, which compile successfully. 

![下载](https://user-images.githubusercontent.com/6810084/101518744-9f88b380-3982-11eb-896e-85f155261cf2.png)

**Comment by awulkiew** [comment]
That's great. The result looks nice too. Thanks for the feedback.
