### ISSUE TITLE
Add test for extensions/test/algorithms/parse.hpp

### ISSUE THREAD

**Issue by mloskot** [boostorg/geometry#788]
It would be helpful to have a test covering features in the [extensions/test/algorithms/parse.hpp](https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/extensions/algorithms/parse.hpp) extension, see https://github.com/boostorg/geometry/pull/786

**Comment by GauravSarkar** [comment]
@mloskot  if you can give a little bit more details on this issue, I was willing to take up the issue.

**Comment by GauravSarkar** [comment]
As far as I have seen there is no parse.hpp under  ```extensions/test/algorithms```. So are you asking to create it and add test results of features as per #786 ?

**Comment by mloskot** [comment]
The file is there, see the link in the issue description that I've just updated.

I don't really have anything to add.
It's a typical procedure: read the code, learn what's the public interface, add test cases and i exercise functions of the public interface.

**Comment by GauravSarkar** [comment]
Thanks @mloskot  I got it. I  will go through the code

**Comment by ayushgupta138** [comment]
@mloskot  could you please provide some more details regarding the issue and about the test cases that needs to added. I am willing to work on this issue, since there hasn't been a pull request lately.

**Comment by mloskot** [comment]
@ayushgupta138 See my earlier comment.

**Comment by RajWorking** [comment]
You want us to create X?
include/boost/geometry/extensions/algorithms/distance_info.hpp : extensions/test/algorithms/distance_info.cpp
include/boost/geometry/extensions/algorithms/parse.hpp : X
X is extensions/test/algorithms/parse.cpp, am I correct?

**Comment by mloskot** [comment]
I think, you've decoded the file structure quite right.

**Comment by ayushgupta138** [comment]
(Assuming parse.hpp is included)
`typedef bg::model::point<double, 2, bg::cs::spherical_equatorial<radian>> earth;`
`earth ear;`
`parse<earth>(ear, "17.65R N", "23.2R W");`
`cout << get<0>(ear) << " " << get<1>(ear) << "\n";`
The above code snippet outputs `-23.2 17.65`
but if space is added between the value and 'R' 
`parse<earth>(ear, "17.65 R N", "23.2 R W");`
the values 17.65 and 23.2 are assumed as degree values and converted to radian outputting  
` -0.404916  0.308051`
Since N/E/W/S are working properly even if spaces are added,
@mloskot  is this a bug or is it functioning the way it should?

**Comment by ayushgupta138** [comment]
@mloskot could you please clarify the above query.

**Comment by mloskot** [comment]
@ayushgupta138  I'm travelling until next week, mostly offline, so I can't check myself.
It's possible there is a bug and some code reading and debugging is needed to confirm.

**Comment by mloskot** [comment]
Regarding question in https://github.com/boostorg/geometry/issues/788#issuecomment-753483434 it looks like these:
- `<number>`
- `<number><unit>` 

are all treated as a single token by design and any following white-space triggers processing of the value:

https://github.com/boostorg/geometry/blob/e710403b4d220ccf1c07c7035f36d1e86d6be75e/include/boost/geometry/srs/projections/impl/dms_parser.hpp#L230-L234

Any other tokens that follow are processed as value-less. 
So, I think there is no bug, if anything, it's just limited flexibility (possible to improve, of course).

**Comment by ayushgupta138** [comment]
I should have been careful about the term 'bug' in my comment. After going through the code of dms_parser.hpp, the details were clear to me(Thanks for the confirmation though). Assuming the same, I have submitted a pr for the unit test. It would really be helpful if you could provide some suggestions on it for further improvement.

**Comment by mloskot** [comment]
Initial implementation of the tests have been added in #809

Further improvements added in #806
