### ISSUE TITLE
Geometry only allows default constructed allocators

### ISSUE THREAD

**Issue by kleunen** [boostorg/geometry#811]
The geometry classes allow overriding the allocators:
https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/geometries/multi_linestring.hpp#L50-L55

However the constructor gives no possibility to provide a reference to the allocator:
https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/geometries/multi_linestring.hpp#L68-L76

As can be done with classes in the STL:
````C++
explicit vector (const allocator_type& alloc = allocator_type());
explicit vector (size_type n);          vector (size_type n, const value_type& val,                  const allocator_type& alloc = allocator_type());
template <class InputIterator>   vector (InputIterator first, InputIterator last,           const allocator_type& alloc = allocator_type());
vector (const vector& x); vector (const vector& x, const allocator_type& alloc);
vector (vector&& x); vector (vector&& x, const allocator_type& alloc);
vector (initializer_list<value_type> il,        const allocator_type& alloc = allocator_type());
````

So only default constructable allocators can beused. 

Can I use non-default constructable allocators somehow ?

**Comment by mloskot** [comment]
It could be possible to register your own models as geometries (e.g. `std::vector` is a valid model for LineString geometry),
but, conceptually, you *may* hit requirement of geometries must be default constructible, I can't remember.
And, a default constructible collection (e.g. `std::vector`) will [require default constructible allocator](https://stackoverflow.com/a/40683807/151641), obviously.

**Comment by kleunen** [comment]
> It could be possible to register your own models as geometries (e.g. `std::vector` is a valid model for LineString geometry),
> but, conceptually, you _may_ hit requirement of geometries must be default constructible, I can't remember.

Yes, it probably depends on which operations you use, whether they would require constructing a temporary object. 
But I already saw that indeed the geometries are just basicly concepts, so maybe it is an option to implement custom geometries

I was also thinking about creating a custom allocator which has a default constructor and uses a global variable for the constructor. But I am a bit stuck on implementing this custom allocator. 

But adding the allocator to the constructor of the geometries would not be a bad idea, i would say.

**Comment by kleunen** [comment]
> By the way, you may also try custom geometry type registration mode.

Ah yes, that does actually work:
https://wandbox.org/permlink/RYKtjklQkMbgxvlk

**Comment by mloskot** [comment]
Yup, `std::vector` is a perfectly support model of geometry.

**Comment by kleunen** [comment]
But no register for polygon it seems, only multipolygon:
https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/adapted/register.html

**Comment by mloskot** [comment]
There are some reasons behind it

https://github.com/boostorg/geometry/blob/b786bd9dd98ce2e72ae9594af1fb2ce8619512e0/example/c06_custom_polygon_example.cpp#L56-L58

Also, trivial polygons without holes can be represented by ring (i.e. custom registered with `BOOST_GEOMETRY_REGISTER_RING`).

**Comment by kleunen** [comment]
I was able to define my own custom data type. But then if I use within (like for example point within custom polygon and point within custom multi_polygon):

````
  mmap::point_t p(10.0, 1.0);
    if(boost::geometry::within(polygon, p))
        std::cout << "Inside" << std::endl;
    else
        std::cout << "Outside" << std::endl;
````

I also have to define the strategy for my own custom type ?

````
/usr/include/boost/geometry/algorithms/detail/within/interface.hpp:87:21: error: no type named ‘type’ in ‘struct boost::geometry::strategy::within::services::default_strategy<mmap::ring_base_t<boost::geometry::model::d2::point_xy<double>, mmap::boost_vector_t, boost::interprocess::node_allocator<boost::geometry::model::d2::point_xy<double>, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family>, boost::interprocess::iset_index>, 64> >, boost::geometry::model::d2::point_xy<double>, boost::geometry::ring_tag, boost::geometry::point_tag, boost::geometry::polygonal_tag, boost::geometry::pointlike_tag, boost::geometry::cartesian_tag, boost::geometry::cartesian_tag>’
````

**Comment by kleunen** [comment]
After some struggles, i think I have it working now.
