### ISSUE TITLE
Area strategies documentation is broken

### ISSUE THREAD

**Issue by vissarion** [boostorg/geometry#817]
This issue appear in `1.75` where the links of available strategies in area documentation are broken see https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/algorithms/area/area_2_with_strategy.html

In `1.74` the documentation is OK. See for example https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_area_cartesian.html

**Comment by ayushgupta138** [comment]
I see that the links in `1.74` which redirect to `1.75` release  
https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_area_cartesian.html
https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_area_spherical.html
https://www.boost.org/doc/libs/1_74_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_area_geographic.html
redirect to 
https://www.boost.org/doc/libs/
instead to the documentation in `1.75` release.
Similarly, the strategy links in https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/algorithms/area/area_2_with_strategy.html
redirects to home page of `boost geometry` documentation.
Also the strategies on the page https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/strategies/
have three area strategies missing -  `strategy_area_spherical`  `strategy_area_cartesian`  `strategy_area_geographic`
But I was unable to find the source code of these html files. @vissarion  Where can I find them?

**Comment by awulkiew** [comment]
@vissarion @ayushgupta138 I probably caused the problem by moving the strategies from `geometry/strategies` to `geometry/strategy` directory but I forgot to update the doxygen script here:
https://github.com/boostorg/geometry/blob/develop/doc/doxy/Doxyfile#L181

**Comment by awulkiew** [comment]
@ayushgupta138 The documentation is automatically generated from source files using `doxygen`, `doxygen_xml2qbk` (the tool we developed converting XML files generated by doxygen to QBK files) and Boost.Quickbook library.

**Comment by ayushgupta138** [comment]
So basically I have to add  ../../../../boost/geometry/strategies/area \  in  https://github.com/boostorg/geometry/blob/develop/doc/doxy/Doxyfile#L181.
Right @awulkiew ?

**Comment by ayushgupta138** [comment]
So basically I have to add 
 ../../../../boost/geometry/strategy/cartesian \
 ../../../../boost/geometry/strategy/geographic \
 ../../../../boost/geometry/strategy/spherical \
in https://github.com/boostorg/geometry/blob/develop/doc/doxy/Doxyfile#L181
Right @awulkiew ?
