### ISSUE TITLE
Inconsistency in intersects() vs. intersection()

### ISSUE THREAD

**Issue by fhw72** [boostorg/geometry#819]
In my application I noticed an inconsistency in behaviour of:

- intersects() vs.
- intersection()

The problem is that intersects() returns true but the subsequent
call to intersection() yields an empty result.

The problem can be reproduced with the following code:

```
#include <iostream>
#include <boost/geometry.hpp>

namespace bg = boost::geometry;
using point_t = bg::model::d2::point_xy<double>;
using polygon_t = bg::model::polygon<point_t>;
using mpolygon_t = bg::model::multi_polygon<polygon_t>;

int main()
{
    polygon_t poly1, poly2;
    mpolygon_t poly3, poly4, poly5;

    bg::read_wkt("POLYGON(("
        "12227.0 4967.0000000000009, 12238.0 4967.0000000000009, "
        "12238.0 4813.0000000000009, 12227.0 4813.0000000000009, "
        "12227.0 4967.0000000000009))", poly1);
    bg::read_wkt("POLYGON(("
        "12254.0 4947.0, 12219.0 4982.0, 12219.0 5020.0, 12254.0 5055.0, "
        "12261.0 5055.0, 12263.0 5055.0, 12283.0 5055.0, 12283.0 4947.0, "
        "12263.0 4947.0, 12261.0 4947.0, 12254.0 4947.0))", poly2);

    bg::intersection(poly1, poly2, poly3);
    bg::difference(poly1, poly3[0], poly4);

    // b0 = true, b1 = false
    bool b0 = bg::intersects(poly2, poly4[0]);
    bg::intersection(poly2, poly4, poly5);
    bool b1 = (poly5.size() != 0);

    std::cout << b0 << b1 << std::endl;
    return 1;
}

```

**Comment by mloskot** [comment]
> ```
> bg::intersection(poly2, poly4, poly5);
> ```

```cpp
using linestring_t = bg::model::linestring<point_t>;
linestring_t int1;
bg::intersection(poly2, poly4, int1);
std::cout << "int1: " << bg::wkt(int1) << std::endl;
```

Output:

```
int1: LINESTRING(12238 4963,12234 4967)
```

**Comment by awulkiew** [comment]
@mloskot You should've probably passed `multi_linestring`. I would be possible to have multiple linestrings/segments in the output.

**Comment by mloskot** [comment]
@awulkiew There is number of possibilities. I just illustrated for this particular input.

**Comment by fhw72** [comment]
I understand that bg::intersection() returns a (multi_)linestring but the real question is:

Shouldn't
`bool b0 = bg::intersects(poly2, poly4[0]);`
return false?

In the code I have poly1 and poly2 and their intersection poly3:
`bg::intersection(poly1, poly2, poly3);`

This intersection is removed from poly1 (result: poly4):
`bg::difference(poly1, poly3[0], poly4);`

That means that there shoudln't be any intersection between poly2 and poly4 anymore?
(If I change the coordinates in poly1 from 4967.0000000000009 to 4967.0 etc.) intersects
return false as expected.

**Comment by mloskot** [comment]
> Shouldn't `bool b0 = bg::intersects(poly2, poly4[0]);` return false?

AFAIKT, the two touch each other and the `touches` relation implies intersection

![image](https://user-images.githubusercontent.com/80741/108981622-306f5100-768d-11eb-80d5-2ac72c39a41e.png)

> This intersection is removed from `poly1` (result: `poly4`): `bg::difference(poly1, poly3[0], poly4);`

Yes, but the operation can not, topologically, remove the [boundary, just the interior (residue)](https://en.wikipedia.org/wiki/Boundary_(topology)).

**Comment by fhw72** [comment]
> Welcome the issues of the float-point robustness?

Can you shed some light on how to deal with it? I didn't find any description of the

BOOST_GEOMETRY_NO_ROBUSTNESS

macro... maybe I've overseen something?

**Comment by vissarion** [comment]
>That means that there shouldn't be any intersection between poly2 and poly4 left?
(If I change the coordinates in poly1 from 4967.0000000000009 to 4967.0 etc.) intersects
return false as expected.

This is not clear at all. Do you change the coordinates before computing the `poly3` and `poly4`? The intersection polygon (`poly3`) seems large enough to suffer from floating point robustness.

**Comment by fhw72** [comment]
Yes... I mean changing BEFORE computing poly3 and poly4 to

```
bg::read_wkt("POLYGON(("
        "12227.0 4967.0000000000000, 12238.0 4967.0000000000000, "
        "12238.0 4813.0000000000000, 12227.0 4813.0000000000000, "
        "12227.0 4967.0000000000000))", poly1);
```

**Comment by vissarion** [comment]
Then I cannot reproduce this behavior on my side. I am still getting the following (blue: poly1, green: poly2, red: the intersection of poly2 and poly4) 
![intersection_example](https://user-images.githubusercontent.com/3660366/108985025-3cf9a680-7699-11eb-86df-19bc730a4f40.png)

**Comment by fhw72** [comment]
Oh... the penny has fallen now. The intersection is still there it's just a line string and

the sample code I used to demonstrate the behavior was slightly different than the code in my
application.

**Comment by mloskot** [comment]
> The intersection is still there it's just a line string

Yes! It's part of the boundary.
