### ISSUE TITLE
Geometry is top 1 with 40G of testing artifacts

### ISSUE THREAD

**Issue by Kojoley** [boostorg/geometry#836]
I was doing `boost-repo\status>..\b2 toolset=msvc-14.2 address-model=64 link=shared variant=debug` and was impressed with artifacts size, of total 119G, geometry is 40G.

top 10:

lib            | artifacts
---------------|-----------
geometry       | ~ 41 204 M
math           | ~ 10 474 M
test           | ~  6 139 M
spirit         | ~  6 061 M
thread         | ~  3 671 M
multiprecision | ~  3 141 M
hana           | ~  3 131 M
numeric        | ~  3 089 M
range          | ~  2 923 M
phoenix        | ~  2 665 M

geometry folder:
folder     | size
-----------|-----------
test       | ~ 23 743 M
index      | ~ 16 695 M
extensions | ~783 803 K

**Comment by awulkiew** [comment]
Yes, AFAIR the library has the greatest number of lines of code of all Boost libraries and 94% test coverage.

Do you think that something is wrong?

**Comment by Kojoley** [comment]
> Yes, AFAIR the library has the greatest number of lines of code of all Boost libraries

That is impressive, I did not know that, but I am a little bit skeptical that it is 30% of the whole Boost code or same as 9 most massive libraries combined.

> 94% test coverage

Well, in my experience, test coverage for template code says literally nothing. When I tried collecting coverage statistics for Spirit it also said a number close to yours, but I know for sure it is just not.

> Do you think that something is wrong?

Marking some symbols (like TMP only stuff) to not have debug information should help a lot, I seen libc++ are doing that, but I do not know how to find most impactful symbols. Probably, forced optimization on functions will also help. I bet your users would be grateful for that too.

top 10 objects file (whole Boost, but it is all from geometry, so I cut the filename prefix):

size     | object
---------|-------------------------------------------------------
473072 K | test\cs_undefined\csundef_relops2.test\...\csundef_relops2.obj
453233 K | test\cs_undefined\csundef_setops2.test\...\csundef_setops2.obj
217125 K | test\cs_undefined\csundef_index.test\...\csundef_index.obj
212077 K | test\algorithms\set_operations\difference\algorithms_difference_multi_spike.test\...\difference_multi_spike.obj
194539 K | index\test\rtree\generated\b3d\rtree_drst_que_b3d.test\...\rtree_drst_que_b3d.obj
191665 K | index\test\rtree\generated\b2d\rtree_drst_que_b2d.test\...\rtree_drst_que_b2d.obj
188703 K | test\algorithms\set_operations\difference\algorithms_difference_multi.test\...\difference_multi.obj
184698 K | test\algorithms\algorithms_is_valid.test\...\is_valid.obj
177108 K | index\test\rtree\generated\b3d\rtree_rst_que_b3d.test\...\rtree_rst_que_b3d.obj
174434 K | index\test\rtree\generated\b2d\rtree_rst_que_b2d.test\...\rtree_rst_que_b2d.obj

**Comment by barendgehrels** [comment]
It might be that we are top 1, but some library has to be number 1...
We have many tests, and many tests use multiple types, this results in a lot of binaries with a large size.
Can we close this issue?

**Comment by awulkiew** [comment]
@barendgehrels I think so. I'm against making the code even more complex by disabling debugging symbols in some of its parts. If the purpose is having smaller test objects then one could pass corresponding compiler flag and disable them altogether for the whole library.

**Comment by barendgehrels** [comment]
All right, agreed, closing.

**Comment by Kojoley** [comment]
> It might be that we are top 1, but some library has to be number 1...

It is 4 times more than the top 2 library, and it is 30% of the whole Boost.

Thanks for trying to do nothing.
