### ISSUE TITLE
Should we enable Discussions at GitHub?

### ISSUE THREAD

**Issue by awulkiew** [boostorg/geometry#903]
This way people could ask questions and propose features without creating Issues. It could also replace gitter which I rarely visit. What do you think @barendgehrels @mloskot @vissarion ?

**Comment by mloskot** [comment]
After some time of using for https://github.com/valhalla/valhalla, I must admit it is a very useful tool, very conveniently integrated with GitHub, and I like it.

**Comment by barendgehrels** [comment]
I don't have experience with it, but I also think it's good because it's well integrated.
