### ISSUE TITLE
Why doesn't boost/geometry support wkb io?

### ISSUE THREAD

**Issue by jievince** [boostorg/geometry#905]
It's very important.

**Comment by mloskot** [comment]
https://github.com/boostorg/geometry/search?q=wkb&type=code

**Comment by awulkiew** [comment]
@jievince WKB is supported as an extension (so not officially released). The fact that it's in the extensions probably means that it's not ready to be released, but I don't really know. You can use it after getting it from the develop branch.

@meastp was working on it (https://github.com/boostorg/geometry/pull/145). If it's important you could consider continuing his work.
