### ISSUE TITLE
dissolve not compiling with new umbrella strategies implementation

### ISSUE THREAD

**Issue by n4z4m3** [boostorg/geometry#944]
Using the dissolve algorithm causes the compiler to fail.
In Visual Studio 2019 with Windows 10, it gives the following error on dissolver.h

Error C2065 'envelope_strategy_type': undeclared identifier

Dissolve (and probably the other algorithms in the extensions) need to be updated to make use of the new umbrella strategies that are part of the latest versions of boost-geometry.

**Comment by awulkiew** [comment]
Thanks!
